# Generated by Django 5.0.6 on 2024-06-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leisure', '0002_post_image_comment_poll_option_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
