# Generated by Django 5.0.6 on 2024-06-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leisure', '0003_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='post',
        ),
    ]
