# Generated by Django 5.0.6 on 2024-06-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
