# Generated by Django 5.0.6 on 2024-06-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
